version: 2

project_name: mbx

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: mbx
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md
      - .env.example

changelog:
  use: github-native
  sort: asc
